In [ ]:
import numpy as np

array1 = np.array([3,0,9,12,6])
array1 = np.sort(array1)

array2 = np.array([[3,2,4], [5,0,1]])
print(np.sort(array2))

array3 = np.array(["banana","cherry", "apple"])
print(np.sort(array3))

array4 = np.array([True,False,True])
print(np.sort(array4))



In [6]:
import numpy as np

arrayX = np.array([[2,1],[3,4]])

arrayY = np.array([[5,6]])

arrayZ = np.array([[8,7],[9,10],[12,11]])

arrayC = np.concatenate((arrayZ, arrayX, arrayY), axis=0)
print(arrayC)

print("\n")

arrayC_sort = np.sort(arrayC)
print(arrayC_sort)

# if you do not specify the axis you want to sort over, it defaults to negative 1 (last shape of the dimenstion of array)


[[ 8  7]
 [ 9 10]
 [12 11]
 [ 2  1]
 [ 3  4]
 [ 5  6]]


[[ 7  8]
 [ 9 10]
 [11 12]
 [ 1  2]
 [ 3  4]
 [ 5  6]]


In [14]:
import numpy as np

xx = np.array([2,1,4,3,5])

xx_sorted = np.argsort(xx)

print(xx_sorted)

for index in xx_sorted:
    print(xx[index])

[1 0 3 2 4]
1
2
3
4
5


In [10]:
import numpy as np
array5 =np.array([[101, 112,133, 224, 235, 76, 207, 148, 319, 110, 338, 174]])
print(array5)
print("\nsorted\n")
print(np.sort(array5, axis=0))

print("\nsorted axis 1\n")
print(np.sort(array5, axis=1))

[[101 112 133 224 235  76 207 148 319 110 338 174]]

sorted

[[101 112 133 224 235  76 207 148 319 110 338 174]]

sorted axis 1

[[ 76 101 110 112 133 148 174 207 224 235 319 338]]


In [18]:
first_names = ("george","abraham", "denzel")
surnames = ("washington", "lincoln", "washington")

ind = np.lexsort((first_names, surnames))
print(ind)
for i in ind:
    print(f"{first_names[i]},{surnames[i]}")

[1 2 0]
abraham,lincoln
denzel,washington
george,washington


In [24]:
tt = ([[[0, 1, 2, 3], [4, 5, 6, 7] ],[ [10, 11, 12, 13], [14, 15, 16, 17] ],[[20, 21, 22, 23], [24, 25, 26, 27]]])


a, b, c = tt

# print(a)
# print(b)
# print(c)

# print(type(c))

a0, a1 = a
print(a0)
print(a1)

print(type(a0))

[0, 1, 2, 3]
[4, 5, 6, 7]
<class 'list'>


In [27]:
example = ([ [ [0, 1, 2, 3], [14, 15, 16, 17] ],[ [20, 21, 22, 23], [34, 35, 36, 37] ],[[40 ,41 ,42, 43], [54, 55, 56, 57] ] ])

[[[a,b,c,d], [e,f,g,h]],[[i,j,k,l], [m,n,o,p]],[[q,r,s,t], [u,v,w,x]]] = example

print(f"first group : {a}, {b}, {c}, {d}")
print(f"second group : {m}, {n}, {o}, {p}")
print(f"third group : {u}, {v}, {w}, {x}")



first group : 0, 1, 2, 3
first group : 34, 35, 36, 37
first group : 54, 55, 56, 57


In [30]:
import numpy as np

array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
# print(array2)

# print(array2[1:])

array3 = np.array([[1,2,3,4],[5,6,7,8]])
print(array3[1,1:3])

arr = np.arrange(12, dtype=np.float_).reshape(3,4)
print(arr)
arr1 = np.array([6,12,15,18])
print(f"narr1: {arr1}\n")



[6 7]


In [35]:
import numpy as np

arr = np.arange(12, dtype=np.float_).reshape(3,4)
print(f"\narr1: {arr}\n")
print(arr.shape)

arr1 = np.array([6,12,15,18])
print(f"n\arr1: {arr1}\n")
print(arr1.shape)

arr2=np.add(arr,arr1)
print(f"\narr2: {arr2}\n")

arr3= np.subtract(arr, arr1)
print(f"narr3: {arr3}\n")

arr4 = np.multiply(arr,arr1)
print(f"\narr4: {arr4}\n")

arr5 = np.divide(arr, arr1)
print(f"narr5: {arr5}\n")


arr1: [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

(3, 4)
nrr1: [ 6 12 15 18]

(4,)

arr2: [[ 6. 13. 17. 21.]
 [10. 17. 21. 25.]
 [14. 21. 25. 29.]]

narr3: [[ -6. -11. -13. -15.]
 [ -2.  -7.  -9. -11.]
 [  2.  -3.  -5.  -7.]]


arr4: [[  0.  12.  30.  54.]
 [ 24.  60.  90. 126.]
 [ 48. 108. 150. 198.]]

narr5: [[0.         0.08333333 0.13333333 0.16666667]
 [0.66666667 0.41666667 0.4        0.38888889]
 [1.33333333 0.75       0.66666667 0.61111111]]



In [39]:
import numpy as np

array1 = np.array([False,False,True,False])
arra2 = np.array([True,True,True,False])

print(np.logical_and(array1, array2))
print(np.logical_or(array1,array2))
print(np.logical_xor(array1,array2))



ValueError: operands could not be broadcast together with shapes (4,) (3,3) 

In [44]:
import numpy as np

a = np.array([[80,95,10],[50,90,60],[30,65,70]])

print(a)
print(f"MEAN: {np.mean(a)}")
print(f"MEAN (rows): {np.mean(a, axis=0)}")
print(f"MEAN (cols): {np.mean(a, axis =1)}")

print(f"MIN: {np.min(a)}")
print(f"MIN (rows): {np.min(a, axis=0)}")
print(f"MIN (cols): {np.min(a, axis=1)}")

print(f"max: {np.max(a)}")
print(f"max (rows): {np.max(a, axis=0)}")
print(f"max (cols): {np.max(a, axis=1)}")

print(f"average: {np.average(a)}")
print(f"average (rows): {np.average(a, axis=0)}")
print(f"average (cols): {np.average(a, axis=1)}")

print(f"sum: {np.sum(a)}")
print(f"sum (rows): {np.sum(a, axis=0)}")
print(f"sum (cols): {np.sum(a, axis=1)}")

print(f"median: {np.median(a)}")
print(f"median (rows): {np.median(a, axis=0)}")
print(f"median (cols): {np.median(a, axis=1)}")

[[80 95 10]
 [50 90 60]
 [30 65 70]]
MEAN: 61.111111111111114
MEAN (rows): [53.33333333 83.33333333 46.66666667]
MEAN (cols): [61.66666667 66.66666667 55.        ]
MIN: 10
MIN (rows): [30 65 10]
MIN (cols): [10 50 30]
max: 95
max (rows): [80 95 70]
max (cols): [95 90 70]
average: 61.111111111111114
average (rows): [53.33333333 83.33333333 46.66666667]
average (cols): [61.66666667 66.66666667 55.        ]
sum: 550
sum (rows): [160 250 140]
sum (cols): [185 200 165]
median: 65.0
median (rows): [50. 90. 60.]
median (cols): [80. 60. 65.]
