In [36]:
import numpy as np
import csv as csv
import time

# dir(np.ndarray)
# help(np.ndarray)

a = np.arange(15)
print('a arrange:\n',a)

a  = a.reshape(3, 5)
print('a reshape:\n',a)

print('a shape:', a.shape)

print('a ndim:',a.ndim)

print('a dtype:',a.dtype.name)

print('a itemsize:',a.itemsize)

print('a size:',a.size)

print('a type:',type( a))

b= np.array([6,7,8])

print('b type:',type(b))
b.shape
b.ndim
b.dtype
b.itemsize
b.size


a arrange:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
a reshape:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
a shape: (3, 5)
a ndim: 2
a dtype: int32
a itemsize: 4
a size: 15
a type: <class 'numpy.ndarray'>
b type: <class 'numpy.ndarray'>


numpy.ndarray